### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by AndorChen** [JuanitoFatas/rspecbook-feedback#1]
### “1.2 本書要求”->“懂 Ruby”
1. “require‘ ”后面的引号应该是多的
2. 脚注3：链接应该是没有括号的
### “有人說什麼紅綠重構,那是什麼?”

有段全是叉叉框，是故意为之还是乱码呢？

![screen shot 2015-12-20 at 16 13 08](https://cloud.githubusercontent.com/assets/436680/11917122/c883c134-a734-11e5-9336-5b8183507b06.png)
### P11

倒数第三段，末尾多了一个句号。
### P16

乱码

![screen shot 2015-12-20 at 16 23 57](https://cloud.githubusercontent.com/assets/436680/11917151/1a37a814-a736-11e5-9ab8-670905a57afb.png)
### 其他
1. TIP 等有专门的句法和输出格式，要不要用呢？[ref](https://leanpub.com/help/manual#leanpub-auto-tips)

**Comment by JuanitoFatas** [comment]
> 有段全是叉叉框，是故意为之还是乱码呢？

是中文，選了不支援中文的字型，我換個字型試試，多謝。

**Comment by JuanitoFatas** [comment]
All fixed, can [re-download the book](https://leanpub.com/rspecbook), thanks :wink:
